# Generated by Django 4.1.5 on 2023-02-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
