# Generated by Django 4.1.5 on 2023-02-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0002_car_plate_number_alter_rent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(through='carbnb_app.Rent', to='carbnb_app.person'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='car_owner', to='carbnb_app.person'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
