# Generated by Django 4.1.5 on 2023-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0003_car_renters_alter_car_owner_alter_rent_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(blank=True, null=True, related_name='rented_cars', through='carbnb_app.Rent', to='carbnb_app.person'),
        ),
    ]
