# Generated by Django 4.1.5 on 2023-02-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0006_remove_person_user2_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
