# Generated by Django 4.1.5 on 2023-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0009_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
