# Generated by Django 4.1.5 on 2023-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0010_alter_car_plate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_message',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='renters',
            field=models.ManyToManyField(related_name='rented_cars', through='carbnb_app.Rent', to='carbnb_app.person'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['plate_number', 'type'], name='car_plate_n_51c654_idx'),
        ),
    ]
