# Generated by Django 4.1.5 on 2023-03-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carbnb_app', '0011_contactmessage_alter_car_renters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Factory',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.IntegerField(unique=True)),
                ('year', models.IntegerField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carbnb_app.factory')),
            ],
            options={
                'db_table': 'Bike',
            },
        ),
    ]
